---
- name: Uninstall brew packages
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ homebrew_uninstall_packages }}"

- block:
  - name: Install brew packages
    homebrew:
      name: "{{ item.name | default(item) }}"
      install_options: "{{ item.install_options | default(omit) }}"
      state: present
    with_items:
      - "{{ homebrew_installed_packages }}" 

  - name: Upgrade all homebrew packages
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
    when: homebrew_upgrade_all_packages
  notify:
    - Clear homebrew cache
