---
- name: Create Homebrew directory
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes

- name: Ensure Homebrew directory has the correct permissions
  file:
    path: "{{ homebrew_prefix }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    state: directory
  become: yes

- name: Install Homebrew dependencies
  package:
    name: "{{ dependencies }}"
    state: present

- name: Install yum groupinstall dependencies
  yum:
    name: "@Development tools"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Fedora dependencies
  yum:
    name: libxcrypt-compat
    state: present
  when: ansible_distribution == "Fedora"
