---
- name: Create Homebrew root directory if it does not exists (macOS >= 10.13)
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    state: directory
  become: yes
  when: "ansible_distribution_version is version('10.13', '>=')"

- name: Create Homebrew root directory if it does not exists (macOS < 10.13)
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    group: admin
    state: directory
  become: yes
  when: "ansible_distribution_version is version('10.13', '<')"

- name: Ensure Homebrew directory exists
  file:
    path: "{{ homebrew_install_path }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    state: directory
    mode: 0775
  become: yes
