---
- name: Ensure the configured taps are tapped
  homebrew_tap:
    tap: "{{ item.name | default(item) }}"
    url: "{{ item.url | default(omit) }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"
