---
- name: Converge
  hosts: all
  become: true

  vars:
    homebrew_clear_cache: true
    hombrew_installed_packages:
      - ssh-copy-id
      - nginx-full
    homebrew_cask_apps:
      - google-chrome
    homebrew_taps:
      - homebrew/core
      - name: denji/nginx
        url: 'https://github.com/denji/homebrew-nginx.git'

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: gonzalezandrew.homebrew
